### ISSUE TITLE
Find module should not be distributed with package

### ISSUE THREAD

**Issue by barcharcraz** [lasote/conan-openssl#24]
Find modules are really not supposed to be distributed with source (or binary) packages. They should be made available for users to add to their own project. This is particularly annoying in this case because CMake provides a very good FindOpenSSL itself. There is no way to prefer the built in module to the one you provide.

Perhaps change from providing a find module to providing a config file.

**Comment by lasote** [comment]
Hi! The findPackage is needed in order to let CMake find the conan package, not the system one. It's usually not needed but with complex libraries (with different names for different configurations) like OpenSSL is required. Sometimes the CMake one are not prepared to find all the possible names of the libraries or search in custom crazy locations like `c:\openssl`and things like that. The thing is if you are requiring OpenSSL with conan you want conan to locate the OpenSSL from your local conan cache, right? So what's the problem?

In any case, you can alter the CMAKE_MODULE_PATH and delete the conan directories or, we could avoid calling `conan_set_find_paths()` from `conan_basic_setup()`, that way CMake won't be able to locate the custom `findOpenSSL.cmake` file.

**Comment by barcharcraz** [comment]
The trouble is that I really want CMAKE_PREFIX_PATH to be set. Not to mention every time this makes it so that you HAVE to build with conan. Would it not be better to have the conanbuildinfo simply set the variables that the system FindOpenSSL uses to locate the library. I'm fairly sure it won't switch to a different library if you've explicitly given it a path.

For now I'm just going to nuke CMAKE_MODULE_PATH, but let it be known that this is extremely annoying.

**Comment by lasote** [comment]
Hi, I'm working on a curated openssl recipe for conan-center. I'm thinking in an alternative to avoid the find_package. Anyway... I understand you would keep working with your findPackage, but maybe for conan is better just to link with the $CONAN_LIBS. Is it valid for you? Thanks

**Comment by barcharcraz** [comment]
this is not valid for me since I want to preserve the ability to use distro
supplied packages. What about simply setting OpenSSL_DIR and friends?

**Comment by lasote** [comment]
Hi, I have completely removed the custom findPackage in this [conan package](https://bintray.com/lasote/conan-repo/OpenSSL%3Aconan). I'm keeping some library common names so now the original CMake findOpenSSL.cmake finds it. 
It's not yet in the conan-center repository, but I hope it will be linked soon. If you could try you need to add my personal repository in the meantime:

```
conan remote add lasote https://api.bintray.com/conan/lasote/conan-repo 
```

The reference is: `OpenSSL/1.0.2l@lasote/stable`.
If you could give me feedback would be great.

Thanks!
